# Generated by Django 4.2.7 on 2023-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home2/media')),
                ('work_image', models.ImageField(upload_to='home2/media')),
                ('title', models.CharField(max_length=20)),
                ('sub_title', models.CharField(max_length=50)),
                ('title_word', models.CharField(max_length=20)),
                ('sub_title_word', models.CharField(max_length=50)),
            ],
        ),
    ]
